config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pokemon_battles#index'
  post 'pokemon/:id', to: 'pokemons#heal', as: 'heal'
  post 'pokemon/', to: 'pokemons#heal_all', as: 'heal_all'
  post 'pokemon_battles/:id', to: 'pokemon_battles#attack', as: 'attack'
  resources :pokemons do 
    resources :pokemon_skills, only: [:create]
  end
  resources :pokedexes
  resources :skills
  resources :pokemon_skills
  resources :pokemon_battles
end

app/models/pokedex.rb
class Pokedex < ApplicationRecord
    has_many :pokemons
end

app/controllers/pokedexes_controller.rb
class PokedexesController < ApplicationController
    def index     
        @pokedexes = Pokedex.paginate(page: params[:page]).order('id')  
    end

    def new 
        @pokedex = Pokedex.new
        @element_type = Elements::ELEMENT_TYPE
    end

    def create 
        @pokedex = Pokedex.new(pokedex_params)
        if @pokedex.save 
            redirect_to pokedexes_url
        end
    end

    def show 
        @pokedex = Pokedex.find(params[:id])
    end

    private 
    def pokedex_params 
        params.require(:pokedex).permit(:name, :base_health_point, :base_attack, :base_defence, :element_type, :image_url)
    end
end

app/helpers/pokedexes_helper.rb
module PokedexesHelper
end

app/views/pokedexes/index.html.erb
<div class="container text-center inline">
    <%= link_to "New", new_pokedex_path, class: "btn btn-success btn-lg float-end" %>
    <h1 class="text-dark">Pokedex</h1>
</div>

<div class="container">
    <table class="table">
      <thead  class="text-center">
        <tr>
          <th scope="col" class="text-center">No.</th>
          <th scope="col" class="text-center">Image</th>
          <th scope="col" class="text-center">Name</th>
          <th scope="col" class="text-center">Action</th>
        </tr>
      </thead>
      <tbody  class="text-center">
        <% @pokedexes.each do |pokedex| %>
          <tr>
              <td><%= pokedex.id %></td>
              <td><%= image_tag pokedex.image_url, style: "width: 100px; height: 100px" %></td>
              <td><%= pokedex.name.capitalize %></td>
              <td><%= link_to "Show", pokedex_path(pokedex), class: "btn btn-primary btn-lg" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="float-end">
        <%= will_paginate %>
    </div>
</div>

app/views/pokedexes/new.html.erb
<div class="container text-center inline">
    <h1 class="text-dark">Add Pokemon</h1>
</div>

<div class="container bg-light">
  <div>
    <%= form_with(model: @pokemon, local: true) do |f| %>
      <div class="form-group">
        <%= f.label :name%>
        <%= f.text_field :name, class: 'form-control', placeholder: 'Name..' %>
      </div>
      <div class="form-group">
        <%= f.label :element_type, "Element Type"%>
        <%= f.select :element_type, Elements::ELEMENT_TYPE.map {|e| [e.capitalize, e]}, {:include_blank => "Element Type"}, class: "form-select form-select-lg" %>
      </div>
      <div class="form-group">
        <%= f.label :base_health_point, "HP"%>
        <%= f.text_field :base_health_point, class: 'form-control', placeholder: 'HP..' %>
      </div>
      <div class="form-group">
        <%= f.label :base_attack, "Attack"%>
        <%= f.text_field :name, class: 'form-control', placeholder: 'Attack..' %>
      </div>
      <div class="form-group">
        <%= f.label :base_defence, "Defence"%>
        <%= f.text_field :base_defence, class: 'form-control', placeholder: 'Defence..' %>
      </div>
      <div class="form-group">
        <%= f.label :image_url, "Image URL"%>
        <%= f.text_field :image_url, class: 'form-control', placeholder: 'Image URL..' %>
      </div>

      <div class="text-center">
        <%= f.submit "Catch!", class: "btn btn-primary btn-lg text-center" %>
      </div>
    <% end %>
  </div>
</div>

app/views/pokedexes/show.html.erb
<div class="container text-center">
  <div class="row align-items-start">
    <div class="col">
        <%= image_tag @pokedex.image_url, style: "width: 450px; height: 450px" %>
    </div>
     <div class="col text-start">
      <div class="bg-light">
          <h1 class="text-dark"><%= @pokedex.name.capitalize %></h1>
          <p class="fs-1">Element Type : <%= @pokedex.element_type.capitalize %></p>
          <p class="fs-1">HP : <%= @pokedex.base_health_point %></p>
          <p class="fs-1">Attack : <%= @pokedex.base_attack %></p>
          <p class="fs-1">Defence : <%= @pokedex.base_defence %></p>
          <p class="fs-1">Speed : <%= @pokedex.base_speed %></p>
      </div> 
    </div>
  </div>
</div>