config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pokemon_battles#index'
  post 'pokemon/:id', to: 'pokemons#heal', as: 'heal'
  post 'pokemon/', to: 'pokemons#heal_all', as: 'heal_all'
  post 'pokemon_battles/:id', to: 'pokemon_battles#attack', as: 'attack'
  resources :pokemons do 
    resources :pokemon_skills, only: [:create]
  end
  resources :pokedexes
  resources :skills
  resources :pokemon_skills
  resources :pokemon_battles
end

app/models/skill.rb
class Skill < ApplicationRecord
    has_many :pokemon_skills
    has_many :pokemons, through: :pokemon_skills
    validates_uniqueness_of :name, on: :create
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
    def index
        @skills = Skill.paginate(page: params[:page]).order('id')
    end

    def new 
        @skill = Skill.new
        @element_type = Elements::ELEMENT_TYPE
    end

    def create 
        @skill = Skill.new(skill_params)
        if @skill.save 
            redirect_to skills_url
        end
    end

    def edit 
        @skill = Skill.find(params[:id])
    end

    def update 
        @skill = Skill.find(params[:id])
        if @skill.update(skill_params)
            redirect_to skills_url
        end
    end

    def destroy 
        Skill.find(params[:id]).destroy
        redirect_to skills_url
    end

    private

    def skill_params 
        params.require(:skill).permit(:name, :power, :max_pp, :element_type)
    end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/skills/edit.html.erb
<div class="container text-center inline">
    <h1 class="text-dark">Edit Skill Stats</h1>
</div>

<div class="container bg-light">
  <div>
    <%= form_with(model: @skill, local: true) do |f| %>
      <div class="form-group">
        <%= f.label :name, "Name"%>
        <%= f.text_field :name, class: 'form-control', placeholder: 'Name..' %>
      </div>
      <div class="form-group">
        <%= f.label :power, "Power"%>
        <%= f.text_field :power, class: 'form-control', placeholder: 'HP..' %>
      </div>
      <div class="form-group">
        <%= f.label :max_pp, "Max PP"%>
        <%= f.text_field :max_pp, class: 'form-control', placeholder: 'Attack..' %>
      </div>
      <div class="form-group">
        <%= f.label :element_type, "Element Type"%>
        <%= f.select :element_type, Elements::ELEMENT_TYPE.map {|e| [e.capitalize, e]}, {:include_blank => "Element Type"}, class: "form-select form-select-lg" %>
      </div>
      <div class="text-center">
        <%= f.submit "Edit", class: "btn btn-primary btn-lg text-center w-25" %>
      </div>
    <% end %>
  </div>
</div>

app/views/skills/index.html.erb
<div class="container text-center">
<%= link_to "New", new_skill_path, class: "btn btn-success btn-lg float-end" %>
    <h1 class="text-dark">Skills</h1>
</div>

<div class="container">
    <table class="table">
      <thead  class="text-center">
        <tr>
          <th scope="col" class="text-center">ID.</th>
          <th scope="col" class="text-center">Name</th>
          <th scope="col" class="text-center">Power</th>
          <th scope="col" class="text-center">Max PP</th>
          <th scope="col" class="text-center">Element Type</th>
          <th scope="col" colspan="3"  class="text-center">Action</th>
        </tr>
      </thead>
      <tbody  class="text-center">
        <% @skills.each do |skill| %>
            <tr>
                <td><%= skill.id %></td>
                <td><%= skill.name.capitalize %></td>
                <td><%= skill.power %></td>
                <td><%= skill.max_pp%></td>
                <td><%= skill.element_type.capitalize %></td>
                <td><%= link_to "Edit", edit_skill_path(skill), class: "btn btn-warning btn-lg" %></td>
                <td><%= link_to "Delete", skill_path(skill), method: :delete, class: "btn btn-danger btn-lg" %></td>
            </tr>
        <% end %>
      </tbody>
    </table>
    <div class="float-end">
        <%= will_paginate %>
    </div>
</div>

app/views/skills/new.html.erb
<div class="container text-center inline">
    <h1 class="text-dark">Add Skill</h1>
</div>

<div class="container bg-light">
  <div>
    <%= form_with(model: @skill, local: true) do |f| %>
      <div class="form-group">
        <%= f.label :name, "Name"%>
        <%= f.text_field :name, class: 'form-control', placeholder: 'Name..' %>
      </div>
      <div class="form-group">
        <%= f.label :power, "Power"%>
        <%= f.text_field :power, class: 'form-control', placeholder: 'HP..' %>
      </div>
      <div class="form-group">
        <%= f.label :max_pp, "Max PP"%>
        <%= f.text_field :max_pp, class: 'form-control', placeholder: 'Attack..' %>
      </div>
      <div class="form-group">
        <%= f.label :element_type, "Element Type"%>
        <%= f.select :element_type, Elements::ELEMENT_TYPE.map {|e| [e.capitalize, e]}, {:include_blank => "Element Type"}, class: "form-select form-select-lg" %>
      </div>

      <div class="text-center">
        <%= f.submit "Submit", class: "btn btn-primary btn-lg text-center" %>
      </div>
    <% end %>
  </div>
</div>