config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pokemon_battles#index'
  post 'pokemon/:id', to: 'pokemons#heal', as: 'heal'
  post 'pokemon/', to: 'pokemons#heal_all', as: 'heal_all'
  post 'pokemon_battles/:id', to: 'pokemon_battles#attack', as: 'attack'
  resources :pokemons do 
    resources :pokemon_skills, only: [:create]
  end
  resources :pokedexes
  resources :skills
  resources :pokemon_skills
  resources :pokemon_battles
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
    belongs_to :pokemon, class_name: "Pokedex", optional: true
    has_many :pokemon_skills, dependent: :destroy
    has_many :skills, through: :pokemon_skills
    has_many :pokemon_battles, dependent: :destroy
    accepts_nested_attributes_for :pokemon_skills
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
    def index
        @pokemons = Pokemon.paginate(page: params[:page]).order('id')
    end

    def show 
        @pokemon = Pokemon.find(params[:id])
        @skill = Skill.where(["element_type = ?", @pokemon.element_type]).order('id')
        
        respond_to do |format| 
            # for default show page in html format
            format.html 
            # to render the dog object in JSON format
            format.json { render json: @pokemon.to_json(:include => :pokemon_skills) }
        end 
    end

    def new
        @pokedexes = Pokedex.all.order('id')
        @pokemon = Pokemon.new
    end

    def create
        @pokemon = Pokemon.new
        
        @pokedex_data = Pokedex.find(params[:pokemon][:pokemon_id])
        @pokemon.pokedex_id = @pokedex_data.id
        @pokemon.name = @pokedex_data.name
        @pokemon.level = 1
        @pokemon.max_health_point = @pokedex_data.base_health_point
        @pokemon.current_health_point = @pokemon.max_health_point
        @pokemon.attack = @pokedex_data.base_attack
        @pokemon.defense = @pokedex_data.base_defence
        @pokemon.speed = @pokedex_data.base_speed
        @pokemon.current_experience = 0
        @pokemon.image_url = @pokedex_data.image_url
        @pokemon.element_type = @pokedex_data.element_type
        
        if @pokemon.save
            flash[:success] = "Pokemon successfully added to field!"
            redirect_to pokemon_path(@pokemon)
        else
            puts @pokemon.errors.full_messages
        end
    end
    
    
    def heal(id: params[:id], heal_all_flag: false)
        @pokemon = Pokemon.find(id)
        @pokemon.current_health_point = @pokemon.max_health_point
            @pokemon.pokemon_skills.each do |skill|
            skill.current_pp = skill.skill.max_pp
            skill.save
        end
        if @pokemon.save
            if heal_all_flag 
                return 
            else
                flash[:success] = "Your pokemon are fighting fit!"
                redirect_to pokemon_path
            end
        end
    end

    def heal_all 
        @pokemons = Pokemon.all.order('id')
        @pokemons.each do |pokemon|
            heal(id: pokemon.id, heal_all_flag: true)
        end
        if @pokemon.save
            flash[:success] = "All of your pokemon are fighting fit!"
            redirect_to pokemons_path
        end
    end

    def edit 
        @pokemon = Pokemon.find(params[:id])
        # @pokemon.pokemon_skills_attributes = @pokemon.pokemon_skills
        # @skill = Skill.all.order('id')
          respond_to do |format| 
            # for default show page in html format
            format.html 
            # to render the pokemon object in JSON format
            format.json { render json: @pokemon.to_json(pokemon: @pokemon, pokemon_skill: @skill ) }
        end 
    end

    def update
        @pokemon = Pokemon.find(params[:id])
        @pokemon.pokemon_skills.destroy_all

        if @pokemon.update(pokemon_params)
            redirect_to pokemon_path
        end
    end

    def destroy 
        Pokemon.find(params[:id]).destroy
        redirect_to pokemons_path
    end

    private

    def pokemon_params 
        params.require(:pokemon).permit(:name, :element_type, :current_health_point, :attack, :defense, :speed, :image_url, pokemon_skills_attributes:[:pokemon_id, :skill_id])
    end
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/pokemons/edit.html.erb
<%= form_for @pokemon do |f| %>
  
  <div class="container text-center">
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
      <%= link_to "Show", pokemon_path(params[:id]), class: "btn btn-primary btn-lg" %>
      <%= link_to "Delete", pokemon_path(params[:id]), method: :delete, class: "btn btn-danger btn-lg" %>
    </div>
  </div>

  <div class="container text-center mb-3">
    <div class="row align-items-start">
      <div class="col">
          <%= image_tag @pokemon.image_url, style: "width: 450px; height: 450px" %>
      </div>
      <div class="container col text-start bg-light">
        <div>
          <div class="row mb-3">
            <%= f.label :name, "Name"%>
            <%= f.text_field :name, class: 'form-control', placeholder: 'Name..' %>
          </div>
          <div class="row mb-3">
            <%= f.label :element_type, "Element Type"%>
            <%= f.select :element_type, Elements::ELEMENT_TYPE.map {|e| [e.capitalize, e]}, {:include_blank => "Element Type"}, class: "form-select form-select-lg" %>
          </div>
          <div class="row mb-3">
            <%= f.label :current_health_point, "HP"%>
            <%= f.text_field :current_health_point, class: 'form-control', placeholder: 'HP..' %>
          </div>
          <div class="row mb-3">
            <%= f.label :attack, "Attack"%>
            <%= f.text_field :attack, class: 'form-control', placeholder: 'Attack..' %>
          </div>
          <div class="row mb-3">
            <%= f.label :defense, "Defence"%>
            <%= f.text_field :defense, class: 'form-control', placeholder: 'Defence..' %>
          </div>
          <div class="row mb-3">
            <%= f.label :speed, "Speed"%>
            <%= f.text_field :speed, class: 'form-control', placeholder: 'Speed..' %>
          </div>
          <div class="row mb-3">
            <%= f.label :image_url, "Image URL"%>
            <%= f.text_field :image_url, class: 'form-control', placeholder: 'Image URL..' %>
          </div>
        </div>
      </div>
    </div>
  </div>

  <div class="text-center">
    <%= f.submit "Edit", class: "btn btn-success btn-lg text-center" %>
  </div>

<% end %>

app/views/pokemons/index.html.erb
<div class="container text-center">
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
      <%= button_to "Heal All", heal_all_path, class: "btn btn-success btn-lg" %>
      <%= link_to "New", new_pokemon_path, class: "btn btn-success btn-lg" %>
    </div>
    <h1 class="text-dark">Pokemon</h1>
</div>

<div class="container">
  <table class="table">
    <thead  class="text-center">
      <tr>
        <th scope="col" class="text-center">No.</th>
        <th scope="col" class="text-center">Image</th>
        <th scope="col" class="text-center">Name</th>
        <th scope="col" colspan="3"  class="text-center">Action</th>
      </tr>
    </thead>
    <tbody  class="text-center">
      <% @pokemons.each do |pokemon| %>
        <tr>
          <td><%= pokemon.id %></td>
          <td><%= image_tag pokemon.image_url, style: "width: 100px; height: 100px" %></td>
          <td><%= pokemon.name.capitalize %></td>
          <td><%= link_to "Show", pokemon_path(pokemon), class: "btn btn-primary btn-lg" %></td>
          <td><%= link_to "Edit", edit_pokemon_path(pokemon), class: "btn btn-warning btn-lg" %></td>
          <td><%= link_to "Delete", pokemon_path(pokemon), method: :delete, class: "btn btn-danger btn-lg" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="float-end">
    <%= will_paginate %>
  </div>
</div>

app/views/pokemons/new.html.erb
<div class="container text-center inline">
    <h1 class="center text-dark">Catch Pokemon!</h1>
</div>

<div class="container bg-light">
  <div>
    <%= form_with(model: @pokemon, local: true) do |f| %>
      <div class="form-group">
        <%= f.label :pokemon_id%>
        <%= f.select "pokemon_id", @pokedexes.map { |p| [p.name.capitalize, p.id]}, {:include_blank => "Pokemon"}, class: "form-select form-select-lg" %>
      </div>
      <div class="text-center">
        <%= f.submit "Catch!", class: "btn btn-primary btn-lg text-center" %>
      </div>
    <% end %>
  </div>
</div>

app/views/pokemons/show.html.erb
<div class="container text-center">
  <div class="d-grid gap-2 d-md-flex justify-content-md-end">
    <%= button_to "Heal", heal_path, class: "btn btn-success btn-lg" %>
    <%= link_to "Edit", edit_pokemon_path(params[:id]), class: "btn btn-warning btn-lg" %>
    <%= link_to "Delete", pokemon_path(params[:id]), method: :delete, class: "btn btn-danger btn-lg" %>
  </div>
</div>

<div class="container text-center">
  <div class="row align-items-start">
    <div class="col">
        <%= image_tag @pokemon.image_url, style: "width: 450px; height: 450px" %>
    </div>
     <div class="col text-start">
      <div class="bg-light">
        <h1 class="text-dark"><%= @pokemon.name.capitalize %></h1>
        <p class="fs-1">Element Type : <%= @pokemon.element_type.capitalize %></p>
        <p class="fs-1">HP : <%= @pokemon.current_health_point %></p>
        <p class="fs-1">Attack : <%= @pokemon.attack %></p>
        <p class="fs-1">Defence : <%= @pokemon.defense %></p>
        <p class="fs-1">Speed : <%= @pokemon.speed %></p>
      </div> 
    </div>
  </div>
</div>

<div class="container text-center">
  <table class="table">
    <thead  class="text-center">
      <tr>
        <th scope="col" class="text-center">Name</th>
        <th scope="col" class="text-center">Power</th>
        <th scope="col" class="text-center">Max PP</th>
        <th scope="col" class="text-center">Current PP</th>
        <th scope="col" class="text-center">Element Type</th>
        <th scope-"col" class="text-center">Action</th>
      </tr>
    </thead>
    <tbody  class="text-center">
      <% @pokemon.pokemon_skills.each do |pokemon_skill| %>
        <tr>
          <td><%= pokemon_skill.skill.name.capitalize %></td>
          <td><%= pokemon_skill.skill.power %></td>
          <td><%= pokemon_skill.skill.max_pp%></td>
          <td><%= pokemon_skill.current_pp%></td>
          <td><%= pokemon_skill.skill.element_type.capitalize %></td>
          <td><%= link_to "Delete Move", pokemon_skill_path(pokemon_skill.id), method: :delete, class: "btn btn-danger btn-lg" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<div class="container">
  <div class="d-grid gap-2 d-md-flex justify-content-md-start">
    <%= form_with(model: @pokemon_skill, url: pokemon_pokemon_skills_path(@pokemon), local: true) do |f| %>
      <%= f.hidden_field :pokemon_id, value: @pokemon.id %>
      <div class="row mb-3">
        <%= f.label :skill_id, "Skill"%>
        <%= f.select :skill_id, @skill.map { |s| [s.name.capitalize, s.id]}, { include_blank: "Move" }, class: "form-select form-select-lg" %>
      </div>
      <div class="row mb-3">
        <%= f.submit "Add Skill", class: "btn btn-success btn-lg text-center" %>
      </div>
    <% end %>
  </div>
</div>

app/views/pokemons/tralala.html.erb
<%= form_for @pokemon do |f| %>
  
  <div class="container text-center">
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
      <%= link_to "Delete", pokemon_path(params[:id]), method: :delete, class: "btn btn-danger btn-lg" %>
    </div>
  </div>

  <div class="container text-center mb-3">
    <div class="row align-items-start">
      <div class="col">
          <%= image_tag @pokemon.image_url, style: "width: 450px; height: 450px" %>
      </div>
      <div class="container col text-start bg-light">
        <div>
          <div class="row mb-3">
            <%= f.label :name, "Name"%>
            <%= f.text_field :name, class: 'form-control', placeholder: 'Name..' %>
          </div>
          <div class="row mb-3">
            <%= f.label :element_type, "Element Type"%>
            <%= f.select :element_type, Elements::ELEMENT_TYPE.map {|e| [e.capitalize, e]}, {:include_blank => "Element Type"}, class: "form-select form-select-lg" %>
          </div>
          <div class="row mb-3">
            <%= f.label :current_health_point, "HP"%>
            <%= f.text_field :current_health_point, class: 'form-control', placeholder: 'HP..' %>
          </div>
          <div class="row mb-3">
            <%= f.label :attack, "Attack"%>
            <%= f.text_field :attack, class: 'form-control', placeholder: 'Attack..' %>
          </div>
          <div class="row mb-3">
            <%= f.label :defense, "Defence"%>
            <%= f.text_field :defense, class: 'form-control', placeholder: 'Defence..' %>
          </div>
          <div class="row mb-3">
            <%= f.label :speed, "Speed"%>
            <%= f.text_field :speed, class: 'form-control', placeholder: 'Speed..' %>
          </div>
          <div class="row mb-3">
            <%= f.label :image_url, "Image URL"%>
            <%= f.text_field :image_url, class: 'form-control', placeholder: 'Image URL..' %>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  <div class="container text-center">
    <div class="d-grid gap-2 d-md-flex justify-content-md-end">
      <%= link_to "Add Skill", '#', id: 'addRowLink', class: "btn btn-success btn-lg" %>
    </div>
  </div>

  <div class="container text-center">
    <table class="table">
      <thead class="text-center">
        <tr>
          <th scope="col" class="text-center">Name</th>
          <th scope="col" class="text-center">Action</th>
        </tr>
      </thead>
      <tbody id="tableBody" class="text-center">
        <% @pokemon.pokemon_skills.each do |p_skill| %>
          <%= f.fields_for :pokemon_skills_attributes do |ps| %>
            <tr>
              <%= ps.hidden_field :pokemon_id %> 
              <td><%= ps.select "skill_id", options_from_collection_for_select(@skill, "id", "name", p_skill.skill_id), {:include_blank => "Move"}, class: "form-select form-select-lg" %></td>
              <td> <%= link_to "Delete Move", pokemon_skill_path(params[:id]), method: :delete, class: "btn btn-danger btn-lg" %></td>
            </tr>
          <% end %>
        <% end %>
        <tr id="templateRow" style="display: none;">
          <td><%= f.select "pokemon_skills", @skill.map {|s| [s.name, s.id]}, { include_blank: "Move" }, class: "form-select form-select-lg" %></td>
          <td><%= link_to "Delete Move", pokemon_skill_path(params[:id]), method: :delete, class: "btn btn-danger btn-lg" %></td>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="text-center">
    <%= f.submit "Edit", class: "btn btn-primary btn-lg text-center" %>
  </div>
<% end %>

<%= javascript_include_tag 'add_row', 'data-turbolinks-eval' => 'false' %>