config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pokemon_battles#index'
  post 'pokemon/:id', to: 'pokemons#heal', as: 'heal'
  post 'pokemon/', to: 'pokemons#heal_all', as: 'heal_all'
  post 'pokemon_battles/:id', to: 'pokemon_battles#attack', as: 'attack'
  resources :pokemons do 
    resources :pokemon_skills, only: [:create]
  end
  resources :pokedexes
  resources :skills
  resources :pokemon_skills
  resources :pokemon_battles
end

app/views/layouts/_nav.html.erb
<nav class="navbar sticky-top navbar-expand-lg navbar-light bg-light">
  <div class="w-100 d-flex flex-row justify-content-between align-items-center">
    <div>
      <%= link_to root_path do %>
        <%= image_tag "pokemon_logo.png", width: "219px", height: "69px"%>
      <% end %>
    </div>
    <div>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse fs-1" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to "Battle", new_pokemon_battle_path, class: "nav-link" %>
          </li>
           <li class="nav-item">
            <%= link_to "Pokemon", pokemons_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Pokedex", pokedexes_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Skill", skills_path, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PokemonRainbowApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">

    <!-- Google Font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Gloock&family=Open+Sans:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;1,300;1,400;1,500;1,600;1,700;1,800&family=Playfair+Display&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
  
     <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body style="background-image: url('<%=asset_path('body_bg.png')%>')">
    <%= render 'layouts/nav' %>
    <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>